<script lang="ts">
  import {enhance} from '$app/forms';
  import type {PageData,ActionData} from './$types';
  let {data,form}:{data:PageData;form:ActionData}=$props();
  let pending=$state(false);
  const action=()=>{pending=true;return async({update}:any)=>{await update();pending=false;};};
</script>
<svelte:head><title>Sources · Growth Engine</title></svelte:head>
<div class="setup-page">
  <div class="setup-heading"><div><p class="eyebrow">Build your pipeline</p><h1>Start with relevance.</h1><p>Add people you can help, or follow accounts your audience engages with.</p></div><form method="POST" action="?/run" use:enhance={action}><button class="primary" disabled={pending || !data.ready || data.demo}>Run the engine</button></form></div>
  {#if form?.message}<div class="flash toast" role="status">{form.message}</div>{/if}
  {#if !data.ready || data.demo}<div class="setup-notice"><strong>Try it before connecting anything.</strong><p>Load three fictional prospects and drafts. You can edit and approve them; they cannot be sent.</p><div class="inline-actions"><form method="POST" action="?/demo" use:enhance={action}><button disabled={pending}>Load demo drafts</button></form><a class="btn" href="/settings">Set up your business</a></div></div>{/if}
  <section class="setup-section"><div class="section-intro"><h2>LinkedIn sources</h2><p>People, companies, and communities whose posts attract your audience. Requires your own Unipile connection.</p></div><div class="field-stack"><form method="POST" action="?/addSeed" use:enhance={action} class="field-stack"><label>Source URL<input name="url" placeholder="https://www.linkedin.com/company/…" required /></label><label>Display name <span class="optional">optional</span><input name="name" maxlength="120" /></label><div><button disabled={pending}>Add source</button></div></form>{#each data.seeds as seed}<div><a href={seed.linkedin_url} target="_blank" rel="noreferrer">{seed.display_name || seed.slug}</a><form method="POST" action="?/toggleSeed" use:enhance={action}><input type="hidden" name="id" value={seed.id} /><button class="quiet" disabled={pending}>{seed.track?'Pause source':'Resume source'}</button></form></div>{:else}<p class="note">No sources yet. Add only accounts relevant to your business.</p>{/each}</div></section>
  <section class="setup-section"><div class="section-intro"><h2>Add a prospect</h2><p>Already know someone who might fit? Add the facts and let the engine assess relevance. No collector account needed.</p></div><form class="field-stack" method="POST" action="?/addProspect" use:enhance={action}><div class="field-grid"><label>Full name<input name="full_name" required maxlength="120" /></label><label>LinkedIn profile<input name="linkedin_url" required placeholder="https://www.linkedin.com/in/…" /></label></div><label>Role or headline<input name="headline" required minlength="5" maxlength="500" /></label><label>Company <span class="optional">optional; verified separately</span><input name="company" maxlength="150" /></label><label>Why might your offer help them?<textarea name="context" required minlength="20" maxlength="3000" rows="3" placeholder="Specific facts you know, with uncertainty made clear. Do not invent a need or pretend they engaged with a post."></textarea></label><div><button disabled={pending}>Add prospect</button></div></form></section>
  <section class="setup-section"><div class="section-intro"><h2>Import a list</h2><p>Up to 500 prospects per CSV. Columns: linkedin_url, full_name, headline, company, context. Reimporting the same URL updates that prospect.</p></div><form method="POST" action="?/importCsv" enctype="multipart/form-data" use:enhance={action} class="field-stack"><label>Prospects CSV<input type="file" name="csv" accept=".csv,text/csv" required /></label><div><button disabled={pending}>Import CSV</button></div><small>Every row needs a real person’s LinkedIn URL and enough context to assess fit.</small></form></section>
  <section class="setup-section"><div class="section-intro"><h2>People in your pipeline</h2><p>The most recent 100 prospects. Held rows need more context or a working AI connection.</p></div><div class="table-scroll"><table class="source-table"><thead><tr><th>Person</th><th>Progress</th></tr></thead><tbody>{#each data.prospects as person}<tr><td><strong>{person.full_name}</strong>{#if person.is_demo}<span class="optional"> · Demo</span>{/if}<br /><small>{person.headline}</small></td><td>{person.state}{#if person.hold_reason}<p>{person.hold_reason}</p>{/if}{#if person.state==='held'}<form method="POST" action="?/retryHold" use:enhance={action}><input type="hidden" name="id" value={person.id} /><button disabled={pending}>Retry after fixing</button></form>{/if}</td></tr>{:else}<tr><td colspan="2">No prospects yet.</td></tr>{/each}</tbody></table></div></section>
  <section class="setup-section"><div class="section-intro"><h2>Recent runs</h2><p>Jobs run while the app is open. Reload to see the latest status.</p></div><div class="table-scroll"><table class="source-table"><thead><tr><th>Stage</th><th>Status</th><th>Started</th></tr></thead><tbody>{#each data.jobs as job}<tr><td>{job.name}</td><td>{job.state}</td><td>{new Date(job.createdon).toLocaleString()}</td></tr>{:else}<tr><td colspan="3">No runs yet.</td></tr>{/each}</tbody></table></div></section>
  <section class="setup-section"><div class="section-intro"><h2>Campaign handoffs</h2><p>Accepted means HeyReach queued the lead. Delivery and replies are tracked in your HeyReach workspace. Uncertain attempts require checking there before retrying.</p></div><div class="table-scroll"><table class="source-table"><thead><tr><th>Person</th><th>Status</th></tr></thead><tbody>{#each data.attempts as attempt}<tr><td>{attempt.full_name}<br /><small>{new Date(attempt.attempted_at).toLocaleString()}</small></td><td>{attempt.status}<br /><small>{attempt.detail || ''}</small>{#if attempt.status==='accepted'}<form method="POST" action="?/outcome" use:enhance={action}><input type="hidden" name="id" value={attempt.touch_id} /><label>Confirmed in HeyReach<select name="kind" aria-label="Confirmed outcome for {attempt.full_name}"><option value="sent">Message sent</option><option value="positive_reply">Interested reply</option><option value="negative_reply">Not interested</option><option value="meeting_booked">Meeting booked</option></select></label><button disabled={pending}>Record outcome</button></form>{/if}</td></tr>{:else}<tr><td colspan="2">Nothing handed off yet.</td></tr>{/each}</tbody></table></div></section>
</div>
